refactored increment_tag to operate on 'major' and 'minor' references (instead of dev and main)

diff --git a/.github/actions/github__increment-tag/action.yml b/.github/actions/github__increment-tag/action.yml
--- a/.github/actions/github__increment-tag/action.yml
+++ b/.github/actions/github__increment-tag/action.yml
@@ -6,13 +6,23 @@ inputs:
     description: 'Package name for finding the version file'
     required: true
   target_branch:
-    description: 'target_branch (only main and dev supported at the moment)'
+    description: 'target_branch'
     required: true
-    # todo, this really should be changed to major and minor (instead of main and dev)
+  release_type:
+    description: 'type of change: major or minor'
+    required: true
 
 runs:
   using: 'composite'
   steps:
+    - name: Validate target_branch
+      shell: bash
+      run: |
+        if [[ "${{ inputs.release_type }}" != "major" && "${{ inputs.release_type }}" != "minor" ]]; then
+          echo "Invalid version_change: ${{ inputs.release_type }}. Only 'major' and 'minor' are supported."
+          exit 1
+        fi
+
     - name: Checkout code
       uses: actions/checkout@v4
       with:
@@ -35,9 +45,9 @@ runs:
       run: git fetch --tags
 
 
-    # WHEN target_branch IS DEV
-    - name: Find and increment latest tag (FOR DEV releases)
-      if: ${{ inputs.target_branch == 'dev' }}
+    # WHEN release_type is MINOR
+    - name: Find and increment latest tag (FOR MINOR releases)
+      if: ${{ inputs.release_type == 'minor' }}
       shell: bash
       #id: latest_tag
       run: |
@@ -57,9 +67,9 @@ runs:
         
         echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
 
-    # WHEN target_branch IS MAIN
-    - name: Find and increment latest tag (FOR MAIN releases)
-      if: ${{ inputs.target_branch == 'main' }}
+    # WHEN target_branch IS MAJOR
+    - name: Find and increment latest tag (FOR MAJOR releases)
+      if: ${{ inputs.release_type == 'major' }}
       shell: bash
       #id: latest_tag
       run: |
